spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sbbaseapi-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:baseapi}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  security:
    enable: false

